name: Validate and deploy application

on:
  pull_request:
  push:
    branches:
      - master
      - release/*

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck-app
      - run: npm run test:database
      - run: npm run build-app
      - name: Deploy to Firebase
        if: github.event_name == 'push'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run deploy
